### PR TITLE
Event and Alarm Managment Framework HLD.

### PR DESCRIPTION
**Pull request by bhaveshdell**
This HLD has been reviewed and approved on the following PR. 
https://github.com/sonic-net/SONiC/pull/761

This PR is created to meet the CLA requirements.

### CODE REVIEW

**Comment by zhangyanzhao** [comment]
The code PR is  tracked in https://github.com/sonic-net/SONiC/pull/761

**Comment by bhavini-gada** [comment]
@qiluo-msft - This new PR has EasyCLA check passed. Please help with the merge so we can start updating code PRs

**Comment by qiluo-msft** [comment]
@renukamanavalan could you check and merge?

**Review by mint570 — APPROVED** [review]
lgtm from me

**Comment by bhavini-gada** [comment]
@renukamanavalan - Can you please help merge this PR?

**Review by renukamanavalan — APPROVED** [review]

**Comment by vboykox** [comment]
Hi! Are there plans to merge this feature?

https://github.com/sonic-net/sonic-buildimage/pull/7813
https://github.com/sonic-net/sonic-mgmt-common/pull/48
https://github.com/sonic-net/sonic-mgmt-framework/pull/85
https://github.com/sonic-net/sonic-swss-common/pull/490
https://github.com/sonic-net/sonic-swss-common/pull/527
https://github.com/sonic-net/sonic-utilities/pull/1695

**Comment by liat-grozovik** [comment]
@vboykox can you please have the list of the PRs in the PR description like recently sent by Yanzhao?
I also suggest to add it to 202305 release planning so reviewers can assign themselves.

**Comment by bmridul** [comment]
@bhaveshdell , Can u pls reply to this question. What is the plan for the following PRs.

> Hi! Are there plans to merge this feature?
> 
> [sonic-net/sonic-buildimage#7813](https://github.com/sonic-net/sonic-buildimage/pull/7813) [sonic-net/sonic-swss-common#490](https://github.com/sonic-net/sonic-swss-common/pull/490) [sonic-net/sonic-mgmt-framework#85](https://github.com/sonic-net/sonic-mgmt-framework/pull/85) [sonic-net/sonic-mgmt-common#48](https://github.com/sonic-net/sonic-mgmt-common/pull/48)

**Pull request merged**
