### PR TITLE
SONIC VRF HLD 1.2

### PR DESCRIPTION
**Pull request by shine4chen**
Nephos cooperate with brcm for this version.
- update on loopback device
- enhance frr template for vrf and static route configuration
- decrease vrf-name len to 15 for kernel limitation

@preetham-singh

### CODE REVIEW

**Comment by shine4chen** [comment]
@prsunny

**Comment by preetham-singh** [comment]
> Route leak support:
> Looks like we have not captured the case "route leaking for directly connected destinations (not thru nexthops) in another VRF", don't we have this use-case?

Connected route leak feature was already supported as part of VRF HLD 1.1.
We missed to list this as part of VRF HLD 1.1. 
@prsunny / @shine4chen 
Perhaps we can update route leak section?

**Comment by shine4chen** [comment]
@venkatmahalingam good point, I will change it.

> VRF_NAME = 1*16VCHAR ;
> 
> This should be 1*15VCHAR ;, please change it.
> 
> root@sonic:/# ip link add Vrf-12345678910 type vrf table 10
> root@sonic:/# ip link add Vrf-123456789101 type vrf table 11
> Error: argument "Vrf-123456789101" is wrong: "name" too long
> 
> root@sonic:/#

@venkatmahalingam good point , thanks. I will change it.

**Comment by shine4chen** [comment]
> > Route leak support:
> > Looks like we have not captured the case "route leaking for directly connected destinations (not thru nexthops) in another VRF", don't we have this use-case?
> 
> Connected route leak feature was already supported as part of VRF HLD 1.1.
> We missed to list this as part of VRF HLD 1.1.
> @prsunny / @shine4chen
> Perhaps we can update route leak section?

@preetham-singh yes , I will update it.

**Comment by shine4chen** [comment]
@prsunny update HLD for acl-redirect schema backward compatibility

**Pull request merged**
